name: beacon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  auto_route: ^10.1.0+1
  dotted_border: ^3.0.1
  duration_picker: ^1.2.0
  firebase_core: ^3.13.1
  flutter:
    sdk: flutter
  flutter_animarker: ^3.2.0
  flutter_bloc: ^9.1.1
  flutter_config: ^2.0.2
  flutter_countdown_timer: ^4.1.0
  flutter_local_notifications: ^19.2.1
  flutter_polyline_points: ^2.1.0
  flutter_slidable: ^4.0.0
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.12
  freezed_annotation: ^3.0.0
  gap: ^3.0.1
  geolocator: ^14.0.1
  get_it: ^8.0.3
  google_maps_flutter: ^2.12.2
  google_sign_in: ^6.3.0
  graphql_flutter: ^5.2.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  location: ^8.0.0
  lottie: ^3.3.1
  modal_progress_hud_nsn: ^0.5.1
  overlay_support: ^2.1.0
  responsive_sizer: ^3.3.1
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  simple_pip_mode: ^1.1.0
  skeleton_text: ^3.0.1
  sliding_up_panel: ^2.0.0+1
  timezone: ^0.10.1
  uni_links: ^0.5.1
  vibration: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
