name: beacon
description: A new Flutter project.

publish_to: "none"

version: 2.0.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  connectivity_plus: any
  cupertino_icons: ^1.0.5
  date_time_picker: ^2.1.0
  duration_picker: ^1.1.1
  flutter:
    sdk: flutter
  flutter_animarker: ^3.2.0
  flutter_config: ^2.0.2
  flutter_countdown_timer: ^4.1.0
  flutter_local_notifications: ^18.0.1
  flutter_polyline_points: ^1.0.0
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  geolocator: any
  geolocator_android: ^4.3.1
  get_it: ^8.0.3
  google_maps_flutter: ^2.5.3
  hive: ^2.2.3
  intl: ^0.17.0
  location: ^8.0.0
  mockito:
  modal_progress_hud_nsn: ^0.5.1
  overlay_support: ^2.1.0
  path_provider: ^2.0.4
  provider: ^6.1.1
  rxdart: ^0.27.7
  share_plus: ^11.0.0
  shared_preferences: ^2.0.7
  responsive_sizer: ^3.3.1
  skeleton_text: ^3.0.1
  sliding_up_panel: ^2.0.0+1
  uni_links: ^0.5.1
  simple_pip_mode: ^1.1.0
  data_connection_checker_nulls: ^0.0.2
  flutter_geocoder_alternative: ^1.0.3
  gap: ^3.0.1
  lottie:
  # routing
  auto_route: ^10.1.0+1

  # state management
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1

  # class comparison
  freezed_annotation: ^3.0.0

  # for dismissable widget
  flutter_slidable:
    git:
      url: https://github.com/letsar/flutter_slidable.git
      ref: master
  graphql_flutter: ^5.1.2
  http: ^0.13.6
  pinput: ^5.0.0
  vibration: ^3.1.3
  firebase_core:
  google_sign_in: ^6.2.1
  change_app_package_name: ^1.5.0
  dotted_border: ^3.0.1
  shimmer: ^3.0.0
  geolocator_web: ^4.1.3
dev_dependencies:
  build_runner: ^2.1.2
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  freezed: ^3.0.0-0.0.dev
  test: ^1.16.5
  hive_generator:
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

dependency_overrides:
  firebase_auth: "4.12.0"
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - images/
    - animations/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-bold.ttf
        - asset: fonts/Inter-black.ttf
        - asset: fonts/Inter-ExtraBold.ttf
        - asset: fonts/Inter-ExtraLight.ttf
        - asset: fonts/Inter-Light.ttf
        - asset: fonts/Inter-Medium.ttf
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-SemiBold.ttf
        - asset: fonts/Inter-Thin.ttf